# Generated by Django 2.2.25 on 2021-12-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Адрес',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='Город',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='Имя',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='Оплачен',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='Почтовый_индекс',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='Фамилия',
        ),
    ]
